if (NOT DEFINED BLIT_ONCE)
	set(BLIT_ONCE TRUE)
	add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/32blit 32blit)

	if (${CMAKE_SYSTEM_NAME} STREQUAL 32blit)
		add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/32blit-stm32 32blit-stm32)
	else()
		add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/32blit-sdl 32blit-sdl)
	endif()
endif ()
