var annotated_dup =
[
    [ "blit", "namespaceblit.html", [
      [ "AudioChannel", "structblit_1_1AudioChannel.html", "structblit_1_1AudioChannel" ],
      [ "MP3Stream", "classblit_1_1MP3Stream.html", "classblit_1_1MP3Stream" ],
      [ "SurfaceTemplate", "structblit_1_1SurfaceTemplate.html", "structblit_1_1SurfaceTemplate" ],
      [ "SurfaceInfo", "structblit_1_1SurfaceInfo.html", "structblit_1_1SurfaceInfo" ],
      [ "APIConst", "structblit_1_1APIConst.html", "structblit_1_1APIConst" ],
      [ "APIData", "structblit_1_1APIData.html", "structblit_1_1APIData" ],
      [ "BufferFile", "structblit_1_1BufferFile.html", "structblit_1_1BufferFile" ],
      [ "FileInfo", "structblit_1_1FileInfo.html", "structblit_1_1FileInfo" ],
      [ "File", "classblit_1_1File.html", "classblit_1_1File" ],
      [ "ButtonState", "structblit_1_1ButtonState.html", "structblit_1_1ButtonState" ],
      [ "Menu", "classblit_1_1Menu.html", "classblit_1_1Menu" ],
      [ "Particle", "structblit_1_1Particle.html", "structblit_1_1Particle" ],
      [ "ParticleGenerator", "structblit_1_1ParticleGenerator.html", "structblit_1_1ParticleGenerator" ],
      [ "ProfilerProbe", "classblit_1_1ProfilerProbe.html", "classblit_1_1ProfilerProbe" ],
      [ "ScopedProfilerProbe", "classblit_1_1ScopedProfilerProbe.html", "classblit_1_1ScopedProfilerProbe" ],
      [ "Profiler", "classblit_1_1Profiler.html", "classblit_1_1Profiler" ],
      [ "RunningAverage", "classblit_1_1RunningAverage.html", "classblit_1_1RunningAverage" ],
      [ "Timer", "structblit_1_1Timer.html", "structblit_1_1Timer" ],
      [ "Tween", "structblit_1_1Tween.html", "structblit_1_1Tween" ],
      [ "GameMetadata", "structblit_1_1GameMetadata.html", "structblit_1_1GameMetadata" ],
      [ "Font", "structblit_1_1Font.html", "structblit_1_1Font" ],
      [ "JPEGImage", "structblit_1_1JPEGImage.html", "structblit_1_1JPEGImage" ],
      [ "BMPHeader", "structblit_1_1BMPHeader.html", "structblit_1_1BMPHeader" ],
      [ "packed_image", "structblit_1_1packed__image.html", "structblit_1_1packed__image" ],
      [ "Pen", "structblit_1_1Pen.html", "structblit_1_1Pen" ],
      [ "Surface", "structblit_1_1Surface.html", "structblit_1_1Surface" ],
      [ "TMX", "structblit_1_1TMX.html", "structblit_1_1TMX" ],
      [ "TileMap", "structblit_1_1TileMap.html", "structblit_1_1TileMap" ],
      [ "MapLayer", "structblit_1_1MapLayer.html", "structblit_1_1MapLayer" ],
      [ "Map", "structblit_1_1Map.html", "structblit_1_1Map" ],
      [ "Mat3", "structblit_1_1Mat3.html", "structblit_1_1Mat3" ],
      [ "Mat4", "structblit_1_1Mat4.html", "structblit_1_1Mat4" ],
      [ "Point", "structblit_1_1Point.html", "structblit_1_1Point" ],
      [ "Rect", "structblit_1_1Rect.html", "structblit_1_1Rect" ],
      [ "Size", "structblit_1_1Size.html", "structblit_1_1Size" ],
      [ "Vec2", "structblit_1_1Vec2.html", "structblit_1_1Vec2" ],
      [ "Vec3", "structblit_1_1Vec3.html", "structblit_1_1Vec3" ]
    ] ]
];