#pragma once

#define NOP()           asm("NOP;")
//#define HIGH(PORT, PIN) PORT->BSRRL = PIN;
//#define LOW(PORT, PIN)  PORT->BSRRH = PIN;
#define HIGH(PORT, PIN) HAL_GPIO_WritePin(PORT, PIN, 1);
#define LOW(PORT, PIN) HAL_GPIO_WritePin(PORT, PIN, 0);

#define DELAY(MS)       HAL_Delay(MS)
#define LED_ONE_ON()    LOW(GPIOC, GPIO_PIN_8);
#define LED_ONE_OFF()   HIGH(GPIOC, GPIO_PIN_8);
#define LED_ONE_FLASH() LOW(GPIOC, GPIO_PIN_8); DELAY(250); HIGH(GPIOC, GPIO_PIN_8); DELAY(250);

#define LED_TWO_ON()    LOW(GPIOC, GPIO_PIN_9);
#define LED_TWO_OFF()   HIGH(GPIOC, GPIO_PIN_9);
#define LED_TWO_FLASH() LOW(GPIOC, GPIO_PIN_9); DELAY(250); HIGH(GPIOC, GPIO_PIN_9); DELAY(250);

#define BACKLIGHT_OFF()      LOW(GPIOE, GPIO_PIN_5);
#define BACKLIGHT_ON()       HIGH(GPIOE, GPIO_PIN_5);

#define LCD_CS(active)    if(active) {LOW(GPIOA, GPIO_PIN_0)} else {HIGH(GPIOA, GPIO_PIN_0)}
#define LCD_RESET()       LOW(GPIOA, GPIO_PIN_2); DELAY(100); HIGH(GPIOA, GPIO_PIN_2); DELAY(100);

#define USB_MODE_COMMS() HAL_GPIO_WritePin(GPIOD, GPIO_PIN_8, 0);
#define USB_MODE_DFU() HAL_GPIO_WritePin(GPIOD, GPIO_PIN_8, 1);