# libavutil-dev libswscale-dev libswresample-dev libavcodec-dev libavformat-dev
LIB32BLIT = ../32blit
LIBS = `sdl2-config --libs`
FFMPEG = /mnt/c/Users/dxdec/Downloads/ffmpeg-snapshot.tar/ffmpeg/build

CXX = g++
CXXFLAGS = -D__STDC_CONSTANT_MACROS -shared -fPIC -std=c++11 `sdl2-config --cflags` -I$(LIB32BLIT) -I$(FFMPEG)/include
LDFLAGS = -L$(FFMEG)/lib

AR = ar
RANLIB = ranlib

all lib32blit:
	$(CXX) $(CXXFLAGS) Main.cpp VideoCapture.cpp -o testbed.o -L $(LIB32BLIT)/build $(LIBS)
	$(AR) -rcs lib32blitTestBed.a testbed.o
	$(RANLIB) lib32blitTestBed.a

lib32blit:
	-$(MAKE) -C $(LIB32BLIT) clean
	$(MAKE) MCU= PREFIX= CXXFLAGS="-fPIC -std=c++11" -C $(LIB32BLIT)