// contrib.hpp
// 32blit GitHub contributors
//
// AUTO GENERATED BY FILE
// PLEASE DO NOT EDIT BY HAND
//
// use tools/update-contributors.py
//

#pragma once
static const char *contributors[] = {
  "a2",
  "ahnlak",
  "ali1234",
  "andreban",
  "AndrewCapon",
  "drisc",
  "dstretch",
  "illbewithee",
  "johnmccabe",
  "LenardG",
  "LordEidi",
  "lowfatcode",
  "Loxrie",
  "lukesadlerhhl",
  "mikerr",
  "mylogon341",
  "ntwyman",
  "Ozzard",
  "Pharap",
  "santtu",
  "sh1boot",
  "shane-powell",
  "ThePythonator",
  "tinwhisker",
  "titimoby",
  "trollied",
  "ymauray",
  "zenodante",
  nullptr
};
static const char *special_thanks[] = {
  "Charlie Birks (Daft-Freak)",
  nullptr
};
