#!/bin/bash

PROJECT=$(echo $1 | sed 's:/*$::')

echo "32blit: Build and flash project $PROJECT"

if [ -d "${PROJECT}" ]
then

	cd $PROJECT

	mkdir -p build.stm32

	cd build.stm32

	echo " - preparing"

	cmake .. -DCMAKE_TOOLCHAIN_FILE=../../../32blit.toolchain # > /dev/null

	echo " - building"

	make -j8 # > /dev/null

	../../../tools/dfu build --force --out $PROJECT.dfu $PROJECT.bin

	echo " - flashing to device (make sure it's in DFU mode!)"

	../../../../32Blit.exe SAVE COM4 $PROJECT.bin
#	../../../tools/wsl-flash $PROJECT.dfu # > /dev/null

	cd ..
	cd ..

	echo "..done! Reset your 32blit and happy hacking! :-)"
fi

if [ ! -d "${PROJECT}" ]
then
	echo "ERROR: Cannot find project $PROJECT. :-("
	exit 1
fi

exit 0
