set(BLIT_BOARD_NAME "PicoSystem")

set(BLIT_BOARD_DEFINITIONS
    AUDIO_BEEP_PIN=PICOSYSTEM_AUDIO_PIN

    LED_R_PIN=PICOSYSTEM_LED_R_PIN
    LED_G_PIN=PICOSYSTEM_LED_G_PIN
    LED_B_PIN=PICOSYSTEM_LED_B_PIN

    LCD_CS_PIN=PICOSYSTEM_LCD_CSN_PIN
    LCD_DC_PIN=PICOSYSTEM_LCD_DC_PIN
    LCD_SCK_PIN=PICOSYSTEM_LCD_SCLK_PIN
    LCD_MOSI_PIN=PICOSYSTEM_LCD_MOSI_PIN
    LCD_BACKLIGHT_PIN=PICOSYSTEM_BACKLIGHT_PIN
    LCD_VSYNC_PIN=PICOSYSTEM_LCD_VSYNC_PIN
    LCD_RESET_PIN=PICOSYSTEM_LCD_RESET_PIN

    USB_PRODUCT_STR="PicoSystem"

    # non-default PWM audio support
    PICO_AUDIO_PWM_MONO_PIN=PICOSYSTEM_AUDIO_PIN
    PICO_AUDIO_PWM_PIO=1
)

blit_driver(audio beep)
blit_driver(display st7789)
blit_driver(input picosystem)
