#pragma once

#define AUDIO_BEEP_PIN PICOSYSTEM_AUDIO_PIN

#define LED_R_PIN PICOSYSTEM_LED_R_PIN
#define LED_G_PIN PICOSYSTEM_LED_G_PIN
#define LED_B_PIN PICOSYSTEM_LED_B_PIN

#define LCD_CS_PIN PICOSYSTEM_LCD_CSN_PIN
#define LCD_DC_PIN PICOSYSTEM_LCD_DC_PIN
#define LCD_SCK_PIN PICOSYSTEM_LCD_SCLK_PIN
#define LCD_MOSI_PIN PICOSYSTEM_LCD_MOSI_PIN
#define LCD_BACKLIGHT_PIN PICOSYSTEM_BACKLIGHT_PIN
#define LCD_VSYNC_PIN PICOSYSTEM_LCD_VSYNC_PIN
#define LCD_RESET_PIN PICOSYSTEM_LCD_RESET_PIN

#define USB_PRODUCT_STR "PicoSystem"
