#pragma once

#define AUDIO_BEEP_PIN PICOSYSTEM_AUDIO_PIN

#define BUTTON_LEFT_PIN  PICOSYSTEM_SW_LEFT_PIN
#define BUTTON_RIGHT_PIN PICOSYSTEM_SW_RIGHT_PIN
#define BUTTON_UP_PIN    PICOSYSTEM_SW_UP_PIN
#define BUTTON_DOWN_PIN  PICOSYSTEM_SW_DOWN_PIN
#define BUTTON_A_PIN     PICOSYSTEM_SW_A_PIN
#define BUTTON_B_PIN     PICOSYSTEM_SW_B_PIN
#define BUTTON_X_PIN     PICOSYSTEM_SW_X_PIN
#define BUTTON_Y_PIN     PICOSYSTEM_SW_Y_PIN

#define LED_R_PIN PICOSYSTEM_LED_R_PIN
#define LED_G_PIN PICOSYSTEM_LED_G_PIN
#define LED_B_PIN PICOSYSTEM_LED_B_PIN

#define DISPLAY_WIDTH 240

#define LCD_CS_PIN PICOSYSTEM_LCD_CSN_PIN
#define LCD_DC_PIN PICOSYSTEM_LCD_DC_PIN
#define LCD_SCK_PIN PICOSYSTEM_LCD_SCLK_PIN
#define LCD_MOSI_PIN PICOSYSTEM_LCD_MOSI_PIN
#define LCD_BACKLIGHT_PIN PICOSYSTEM_BACKLIGHT_PIN
#define LCD_VSYNC_PIN PICOSYSTEM_LCD_VSYNC_PIN
#define LCD_RESET_PIN PICOSYSTEM_LCD_RESET_PIN

#define USB_PRODUCT_STR "PicoSystem"
