#!/bin/bash

FILENAME_SRC=$1
FILENAME_TGT=$(echo $FILENAME_SRC | sed 's/\.bin/\.dfu/')

BASE_DIR=`dirname $0`

# Do some rudimentary path fiddling for Windows-compatible path names
FILEPATH_WIN=$(pwd | sed 's/\//\\/g' | sed 's/\\mnt\\c/C:/')\\
FILENAME_WIN=$(echo $FILENAME_TGT | sed 's/\//\\/g')

if [ "$FILENAME_SRC" == "" ]; then
    echo "Usage: $0 <project-name>"
    exit 1
fi

$BASE_DIR/dfu --verbose build --force --out $FILENAME_TGT $FILENAME_SRC

# Call DfuSeCommand.exe
# Ideally you should use the modified version at https://github.com/pimoroni/DfuSE/ since it will reset the hardware after flashing
/mnt/c/Program\ Files\ \(x86\)/STMicroelectronics/Software/DfuSe\ v3.0.6/Sources/Binary/Release/DfuSeCommand.exe -c -d --r --fn "$FILEPATH$FILENAME_WIN"
